import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CreateCustomerModal from "./components/modals/CreateCustomerModal";
import ClientOnly from "./components/ClientOnly";
import RecordPointsModal from "./components/modals/RecordCustomerPointsAndRewardsModal";
import RedeemCustomerRewardsModal from "./components/modals/RedeemCustomerRewardsModal";
import ShareYourPageModal from "./components/modals/ShareYourPageModal";
import RecordCustomerPointsAndRewardsModal from "./components/modals/RecordCustomerPointsAndRewardsModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClientOnly>
        <CreateCustomerModal />
        <RecordCustomerPointsAndRewardsModal />
        <RedeemCustomerRewardsModal />
        <ShareYourPageModal />
      </ClientOnly>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
